// ============================================
// ZenPy - Main Server
// Express + Socket.io + JSON Database
// ============================================
require('dotenv').config();
const express = require('express');
const http = require('http');
const { Server } = require('socket.io');
const path = require('path');
const fs = require('fs');
const cors = require('cors');
const { createJsonStore } = require('./supabaseStore');

const app = express();
const server = http.createServer(app);
const io = new Server(server, { cors: { origin: '*' } });

// --- Middleware ---
app.use(cors());
app.use(express.json());
const session = require('express-session');
const passport = require('passport');
app.use(session({
    secret: process.env.JWT_SECRET || 'zenpy_secret',
    resave: false,
    saveUninitialized: false,
    cookie: { secure: false } // Change to true if using HTTPS in prod
}));
app.use(passport.initialize());
app.use(passport.session());

app.use(express.static(path.join(__dirname, '..', '..', 'frontend', 'public')));
app.use('/css', express.static(path.join(__dirname, '..', '..', 'frontend', 'css')));
app.use('/js', express.static(path.join(__dirname, '..', '..', 'frontend', 'js')));
app.use('/assets', express.static(path.join(__dirname, '..', '..', 'frontend', 'assets')));

// --- Data Directory ---
const DATA_DIR = path.join(__dirname, '..', '..', 'database', 'data');
const dataFiles = {
    'users.json': [],
    'progress.json': [],
    'banned.json': [],
    'global_chat_messages.json': [],
    'activity_log.json': [],
    'follows.json': [],
    'direct_messages.json': [],
    'promo_codes.json': [],
    'questions.json': [],
    'shop_items.json': []
};

const jsonStore = createJsonStore({
    dataDir: DATA_DIR,
    keys: Object.keys(dataFiles),
    defaults: dataFiles,
    tableName: process.env.SUPABASE_JSON_TABLE || 'json_store',
    logger: console,
    localMirror: String(process.env.SUPABASE_LOCAL_MIRROR || 'false').toLowerCase() === 'true'
});

app.locals.readJSON = (filename) => jsonStore.readJSON(filename);
app.locals.writeJSON = (filename, data) => jsonStore.writeJSON(filename, data);
app.locals.DATA_DIR = DATA_DIR;

const SHOP_ASSETS_DIR = path.join(__dirname, '..', '..', 'frontend', 'assets', 'shop');

function toSlug(value = '') {
    return String(value)
        .toLowerCase()
        .replace(/\.[^.]+$/, '')
        .replace(/[^a-z0-9]+/g, '_')
        .replace(/^_+|_+$/g, '');
}

function toTitle(value = '') {
    return String(value)
        .replace(/\.[^.]+$/, '')
        .replace(/[_-]+/g, ' ')
        .replace(/\s+/g, ' ')
        .trim()
        .replace(/\b\w/g, ch => ch.toUpperCase());
}

function getShopItems() {
    const baseItems = app.locals.readJSON('shop_items.json');
    const items = Array.isArray(baseItems) ? [...baseItems] : [];
    const existingIds = new Set(items.map(item => item.id));
    const existingAssets = new Set(
        items
            .map(item => item.assetPath)
            .filter(Boolean)
            .map(asset => path.basename(asset).toLowerCase())
    );

    if (!fs.existsSync(SHOP_ASSETS_DIR)) return items;

    const gifFiles = fs
        .readdirSync(SHOP_ASSETS_DIR)
        .filter(file => /\.gif$/i.test(file))
        .sort((a, b) => a.localeCompare(b));

    let generatedCount = 0;
    gifFiles.forEach((fileName) => {
        const fileLower = fileName.toLowerCase();
        if (existingAssets.has(fileLower)) return;

        const slug = toSlug(fileName);
        if (!slug) return;

        let generatedId = `banner_video_auto_${slug}`;
        let suffix = 2;
        while (existingIds.has(generatedId)) {
            generatedId = `banner_video_auto_${slug}_${suffix}`;
            suffix += 1;
        }

        existingIds.add(generatedId);
        existingAssets.add(fileLower);
        generatedCount += 1;

        items.push({
            id: generatedId,
            name: `${toTitle(fileName)} Motion Banner`,
            description: 'Auto-generated premium GIF banner from your latest shop upload.',
            category: 'profile_banner',
            rarity: 'legendary',
            price: 9000 + (generatedCount * 200),
            cssClass: null,
            assetPath: `/assets/shop/${encodeURIComponent(fileName)}`,
            requirement: {
                type: 'questions',
                value: 210 + (generatedCount * 5)
            },
            isAutoGenerated: true
        });
    });

    return items;
}

app.locals.getShopItems = getShopItems;

app.locals.getBannerAsset = function(itemId) {
    if (!itemId) return null;
    const items = getShopItems();
    const item = items.find(i => i.id === itemId);
    if (!item || item.category !== 'profile_banner') return null;
    return item.assetPath || null;
};

// Utility to convert an item ID into its CSS class globally
app.locals.getItemCssClass = function(itemId) {
    if (!itemId) return null;
    const items = getShopItems();
    const item = items.find(i => i.id === itemId);
    return item ? (item.cssClass || null) : itemId;
};

// --- Ensure avatars directory ---
const avatarsDir = path.join(__dirname, '..', '..', 'frontend', 'assets', 'avatars');
if (!fs.existsSync(avatarsDir)) fs.mkdirSync(avatarsDir, { recursive: true });

// --- Mount Routes ---
const authRoutes = require('./authRoutes');
const userRoutes = require('./userRoutes');
const questionRoutes = require('./questionRoutes');
const leaderboardRoutes = require('./leaderboardRoutes');
const uploadRoutes = require('./uploadRoutes');
const communityRoutes = require('./communityRoutes');
const dmRoutes = require('./dmRoutes');

authRoutes(app);
userRoutes(app);
questionRoutes(app);
leaderboardRoutes(app);
uploadRoutes(app);
communityRoutes(app);
dmRoutes(app);

// --- Chat Server (Socket.io) ---
const chatServer = require('./chatServer');
chatServer(io, app.locals.readJSON, app.locals.writeJSON, app.locals.getItemCssClass);

// --- Serve Pages ---
app.get('/', (req, res) => res.sendFile(path.join(__dirname, '..', '..', 'frontend', 'public', 'index.html')));
app.get('/login', (req, res) => res.sendFile(path.join(__dirname, '..', '..', 'frontend', 'public', 'login.html')));
app.get('/verify', (req, res) => res.sendFile(path.join(__dirname, '..', '..', 'frontend', 'public', 'verify.html')));
app.get('/signup', (req, res) => res.sendFile(path.join(__dirname, '..', '..', 'frontend', 'public', 'signup.html')));
app.get('/forgot-password', (req, res) => res.sendFile(path.join(__dirname, '..', '..', 'frontend', 'public', 'forgot-password.html')));
app.get('/dashboard', (req, res) => res.sendFile(path.join(__dirname, '..', '..', 'frontend', 'public', 'dashboard.html')));
app.get('/practice', (req, res) => res.sendFile(path.join(__dirname, '..', '..', 'frontend', 'public', 'practice.html')));
app.get('/profile', (req, res) => res.sendFile(path.join(__dirname, '..', '..', 'frontend', 'public', 'profile.html')));
app.get('/leaderboard', (req, res) => res.sendFile(path.join(__dirname, '..', '..', 'frontend', 'public', 'leaderboard.html')));
app.get('/shop', (req, res) => res.sendFile(path.join(__dirname, '..', '..', 'frontend', 'public', 'shop.html')));
app.get('/chat', (req, res) => res.sendFile(path.join(__dirname, '..', '..', 'frontend', 'public', 'chat.html')));
app.get('/community', (req, res) => res.sendFile(path.join(__dirname, '..', '..', 'frontend', 'public', 'community.html')));
app.get('/docs', (req, res) => res.sendFile(path.join(__dirname, '..', '..', 'frontend', 'public', 'docs.html')));
app.get('/terms', (req, res) => res.sendFile(path.join(__dirname, '..', '..', 'frontend', 'public', 'terms.html')));
app.get('/rules', (req, res) => res.sendFile(path.join(__dirname, '..', '..', 'frontend', 'public', 'rules.html')));
app.get('/admin', (req, res) => res.sendFile(path.join(__dirname, '..', '..', 'frontend', 'public', 'admin.html')));

app.get('/api/health', (req, res) => {
    res.json({
        success: true,
        status: 'ok',
        storageMode: jsonStore.getMode(),
        timestamp: new Date().toISOString()
    });
});

// --- Start Server ---
const PORT = process.env.PORT || 3000;

async function bootstrap() {
    await jsonStore.init();

    server.listen(PORT, () => {
        console.log(`\n🚀 ZenPy server running on http://localhost:${PORT}`);
        console.log(`📁 Data directory: ${DATA_DIR}`);
        console.log(`🗄️ Storage mode: ${jsonStore.getMode()}`);
        console.log(`🎮 Ready to code!\n`);
    });
}

bootstrap().catch((error) => {
    console.error('Failed to bootstrap server:', error.message);
    process.exit(1);
});

['SIGINT', 'SIGTERM'].forEach((signal) => {
    process.on(signal, async () => {
        try {
            await jsonStore.flushNow();
        } catch (error) {
            console.error('Failed to flush data on shutdown:', error.message);
        }
        process.exit(0);
    });
});
