// Script to generate questions.json — NO pre-filled answers
const fs = require('fs');
const path = require('path');

const questions = [
  // Phase 0: The Absolute Basics (1-10)
  // Questions 1-5 are subjective / user-choice: accept any valid code that compiles
  {id:1,title:"Print Your Name",description:"Write a program that prints your name to the screen using `print()`.",difficulty:"beginner",category:"Phase 0: Basics",concepts:["print"],initialCode:"",hints:["Use the print() function with your name in quotes"],optimalTime:30,xpBase:10,subjective:true,testCases:[{type:"line_count",expectedLines:1,description:"Must output at least 1 line"}]},
  {id:2,title:"Print Multiple Lines",description:"Print your name, your age, and your favorite color, each on a separate line, using three separate `print` statements.",difficulty:"beginner",category:"Phase 0: Basics",concepts:["print","multiple statements"],initialCode:"",hints:["Use three separate print() calls, one for each item"],optimalTime:45,xpBase:20,subjective:true,testCases:[{type:"line_count",expectedLines:3,description:"Must output exactly 3 lines"}]},
  {id:3,title:"Variables",description:"Create a variable called `name` and assign it your name. Then print `My name is` followed by the variable.",difficulty:"beginner",category:"Phase 0: Basics",concepts:["variables","string concatenation"],initialCode:"",hints:["Use = to assign a value", "Use print('My name is', name)"],optimalTime:45,xpBase:30,subjective:true,testCases:[{type:"output_contains",mustContain:"My name is",description:"Output must contain 'My name is'"}]},
  {id:4,title:"Simple Arithmetic",description:"Create two variables `a = 5` and `b = 3`. Print the result of `a + b`, `a - b`, `a * b`, and `a / b` each on separate lines.",difficulty:"beginner",category:"Phase 0: Basics",concepts:["arithmetic","variables"],initialCode:"",hints:["Use print() with arithmetic operators +, -, *, /"],optimalTime:60,xpBase:40,testCases:[{input:"",expectedOutput:"8\n2\n15\n1.6666666666666667",hidden:false}]},
  {id:5,title:"User Input",description:"Ask the user for their name using `input()`, store it in a variable, and then print a greeting like `Hello, [name]!` using an f-string.",difficulty:"beginner",category:"Phase 0: Basics",concepts:["input","f-strings"],initialCode:"",hints:["Use input('Enter your name: ') to get user input","Use f'Hello, {name}!' to format"],optimalTime:60,xpBase:50,testCases:[{input:"Alice",expectedOutput:"Hello, Alice!",hidden:false},{input:"Bob",expectedOutput:"Hello, Bob!",hidden:true}]},
  {id:6,title:"String Concatenation",description:"Ask for first name and last name separately using `input()`, then print the full name by concatenating them with a space in between.",difficulty:"beginner",category:"Phase 0: Basics",concepts:["input","concatenation"],initialCode:"",hints:["Use + to concatenate strings","Don't forget the space: first + ' ' + last"],optimalTime:60,xpBase:60,testCases:[{input:"John\nDoe",expectedOutput:"John Doe",hidden:false}]},
  {id:7,title:"Type Conversion",description:"Ask the user for a number (as a string via `input()`), convert it to an integer using `int()`, multiply it by 2, and print the result.",difficulty:"beginner",category:"Phase 0: Basics",concepts:["int()","type conversion"],initialCode:"",hints:["Use int() to convert string to integer","num = int(input(...))"],optimalTime:60,xpBase:70,testCases:[{input:"5",expectedOutput:"10",hidden:false},{input:"12",expectedOutput:"24",hidden:true}]},
  {id:8,title:"Working with Strings",description:'Create a variable `sentence = "The quick brown fox jumps over the lazy dog"`. Print the length of the sentence using `len()`. Then print the first 10 characters using slicing.',difficulty:"beginner",category:"Phase 0: Basics",concepts:["len()","slicing"],initialCode:"",hints:["Use len(sentence) for length","Use sentence[:10] for first 10 chars"],optimalTime:60,xpBase:80,testCases:[{input:"",expectedOutput:"43\nThe quick ",hidden:false}]},
  {id:9,title:"Lists Introduction",description:'Create a list `fruits = ["apple", "banana", "cherry"]`. Print the list, then print the first element and the last element.',difficulty:"beginner",category:"Phase 0: Basics",concepts:["lists","indexing"],initialCode:"",hints:["Use fruits[0] for first, fruits[-1] for last"],optimalTime:60,xpBase:90,testCases:[{input:"",expectedOutput:"['apple', 'banana', 'cherry']\napple\ncherry",hidden:false}]},
  {id:10,title:"List Operations",description:'Start with `fruits = ["apple", "banana", "cherry"]`. Append "orange" to the list, then remove "banana". Print the final list.',difficulty:"beginner",category:"Phase 0: Basics",concepts:["append","remove"],initialCode:"",hints:["Use .append('orange') and .remove('banana')"],optimalTime:60,xpBase:100,testCases:[{input:"",expectedOutput:"['apple', 'cherry', 'orange']",hidden:false}]},

  // Phase 1: Control Flow (11-20)
  {id:11,title:"Even or Odd",description:"Ask the user for a number using `input()` and print whether it is `Even` or `Odd` using an `if` statement and the modulo operator `%`.",difficulty:"beginner",category:"Phase 1: Control Flow",concepts:["if/else","modulo"],initialCode:"",hints:["Use num % 2 == 0 to check if even"],optimalTime:60,xpBase:110,testCases:[{input:"4",expectedOutput:"Even",hidden:false},{input:"7",expectedOutput:"Odd",hidden:true}]},
  {id:12,title:"Largest of Three",description:"Ask for three numbers using `input()` and print the largest one. Do NOT use the built-in `max()` function.",difficulty:"beginner",category:"Phase 1: Control Flow",concepts:["if/elif/else","comparison"],initialCode:"",hints:["Use if/elif/else to compare all three"],optimalTime:90,xpBase:120,testCases:[{input:"3\n7\n5",expectedOutput:"7",hidden:false},{input:"10\n2\n8",expectedOutput:"10",hidden:true}]},
  {id:13,title:"For Loop - Sum",description:"Use a `for` loop with `range()` to calculate the sum of all numbers from 1 to 100. Print the result.",difficulty:"beginner",category:"Phase 1: Control Flow",concepts:["for loop","range","sum"],initialCode:"",hints:["Use range(1, 101)","Keep a running total variable"],optimalTime:60,xpBase:130,testCases:[{input:"",expectedOutput:"5050",hidden:false}]},
  {id:14,title:"While Loop - Countdown",description:'Use a `while` loop to print numbers from 10 down to 1, then print "Blast off!" at the end.',difficulty:"beginner",category:"Phase 1: Control Flow",concepts:["while loop"],initialCode:"",hints:["Start with n = 10, loop while n >= 1, decrement each iteration"],optimalTime:60,xpBase:140,testCases:[{input:"",expectedOutput:"10\n9\n8\n7\n6\n5\n4\n3\n2\n1\nBlast off!",hidden:false}]},
  {id:15,title:"Loop through a List",description:'Given `fruits = ["apple", "banana", "cherry"]`, use a `for` loop to print each fruit on a separate line.',difficulty:"beginner",category:"Phase 1: Control Flow",concepts:["for loop","lists"],initialCode:"",hints:["for fruit in fruits: print(fruit)"],optimalTime:45,xpBase:150,testCases:[{input:"",expectedOutput:"apple\nbanana\ncherry",hidden:false}]},
  {id:16,title:"List Sum",description:"Given `numbers = [4, 7, 2, 9, 5]`, write a `for` loop to calculate the sum. Do NOT use the built-in `sum()` function. Print the result.",difficulty:"beginner",category:"Phase 1: Control Flow",concepts:["for loop","accumulator"],initialCode:"",hints:["Create a total = 0 variable, add each number in the loop"],optimalTime:60,xpBase:160,testCases:[{input:"",expectedOutput:"27",hidden:false}]},
  {id:17,title:"Find Maximum in List",description:"Using a loop, find the largest number in `[3, 7, 2, 9, 5]` without using `max()`. Print the result.",difficulty:"beginner",category:"Phase 1: Control Flow",concepts:["for loop","max finding"],initialCode:"",hints:["Track the largest number seen so far in a variable"],optimalTime:60,xpBase:170,testCases:[{input:"",expectedOutput:"9",hidden:false}]},
  {id:18,title:"Break - Find First Even",description:"Write a loop over `[3, 7, 8, 2, 9]` that uses `break` to stop when it finds the first even number. Print that number.",difficulty:"beginner",category:"Phase 1: Control Flow",concepts:["break"],initialCode:"",hints:["Use if num % 2 == 0: print(num); break"],optimalTime:60,xpBase:180,testCases:[{input:"",expectedOutput:"8",hidden:false}]},
  {id:19,title:"Continue - Skip Multiples of 3",description:"Print numbers from 1 to 20, but skip any number divisible by 3. Use `continue` to skip.",difficulty:"beginner",category:"Phase 1: Control Flow",concepts:["continue"],initialCode:"",hints:["Use if i % 3 == 0: continue"],optimalTime:60,xpBase:190,testCases:[{input:"",expectedOutput:"1\n2\n4\n5\n7\n8\n10\n11\n13\n14\n16\n17\n19\n20",hidden:false}]},
  {id:20,title:"Nested Loop - Multiplication Table",description:"Print the multiplication table for numbers 1 through 5 in a grid format using nested loops. Each row should have numbers separated by spaces.",difficulty:"intermediate",category:"Phase 1: Control Flow",concepts:["nested loops"],initialCode:"",hints:["Use two for loops","Use print(i*j, end=' ') and print() for newline"],optimalTime:120,xpBase:200,testCases:[{input:"",expectedOutput:"1 2 3 4 5\n2 4 6 8 10\n3 6 9 12 15\n4 8 12 16 20\n5 10 15 20 25",hidden:false}]},

  // Phase 2: Functions (21-30)
  {id:21,title:"Simple Function",description:'Write a function called `greet()` that prints "Hello, welcome!" when called. Then call the function.',difficulty:"beginner",category:"Phase 2: Functions",concepts:["def","functions"],initialCode:"",hints:["def greet(): print('Hello, welcome!')"],optimalTime:45,xpBase:210,testCases:[{input:"",expectedOutput:"Hello, welcome!",hidden:false}]},
  {id:22,title:"Function with Parameter",description:'Write a function `greet_person(name)` that prints "Hello, [name]!". Call it with any name you like.',difficulty:"beginner",category:"Phase 2: Functions",concepts:["parameters"],initialCode:"",hints:["def greet_person(name): print(f'Hello, {name}!')"],optimalTime:60,xpBase:220,subjective:true,testCases:[{type:"output_contains",mustContain:"Hello,",description:"Output must contain 'Hello,'"}]},
  {id:23,title:"Return Value",description:"Write a function `add(a, b)` that returns the sum of a and b. Call it with `add(5, 3)` and print the result.",difficulty:"beginner",category:"Phase 2: Functions",concepts:["return"],initialCode:"",hints:["Use return a + b"],optimalTime:60,xpBase:230,testCases:[{input:"",expectedOutput:"8",hidden:false}]},
  {id:24,title:"Function with Default Parameter",description:"Write a function `power(base, exponent=2)` that returns base raised to exponent. Print `power(3)` and `power(2, 3)`.",difficulty:"beginner",category:"Phase 2: Functions",concepts:["default parameters"],initialCode:"",hints:["def power(base, exponent=2): return base ** exponent"],optimalTime:60,xpBase:240,testCases:[{input:"",expectedOutput:"9\n8",hidden:false}]},
  {id:25,title:"Multiple Return Values",description:"Write a function `get_min_max(numbers)` that returns both the minimum and maximum values from a list as a tuple. Test with `[3, 1, 9, 4, 7]`.",difficulty:"intermediate",category:"Phase 2: Functions",concepts:["multiple returns","tuples"],initialCode:"",hints:["Return a tuple: return (min_val, max_val)","Don't use min() or max()"],optimalTime:90,xpBase:250,testCases:[{input:"",expectedOutput:"(1, 9)",hidden:false}]},
  {id:26,title:"Docstrings",description:'Write a function `get_min_max` with a docstring that says "Returns the minimum and maximum values from a list." Then print the docstring using `print(get_min_max.__doc__)`.',difficulty:"beginner",category:"Phase 2: Functions",concepts:["docstrings","__doc__"],initialCode:"",hints:["Use triple quotes inside the function as first line"],optimalTime:60,xpBase:260,testCases:[{input:"",expectedOutput:"Returns the minimum and maximum values from a list.",hidden:false}]},
  {id:27,title:"Scope",description:"Create a variable `x = 10` outside a function. Write a function that modifies x to 20 using `global`. Print x before and after calling the function.",difficulty:"intermediate",category:"Phase 2: Functions",concepts:["scope","global"],initialCode:"",hints:["Use the global keyword inside the function"],optimalTime:90,xpBase:270,testCases:[{input:"",expectedOutput:"10\n20",hidden:false}]},
  {id:28,title:"Using Functions from Previous Problems",description:"Write a function `calculate_average(numbers)` that returns the average. Use it on `[1, 2, 3, 4, 5]` and print the result.",difficulty:"intermediate",category:"Phase 2: Functions",concepts:["function composition"],initialCode:"",hints:["Sum the numbers, divide by len()"],optimalTime:90,xpBase:280,testCases:[{input:"",expectedOutput:"3.0",hidden:false}]},
  {id:29,title:"Recursion - Factorial",description:"Write a recursive function `factorial(n)` that returns n!. Print `factorial(5)` (should be 120).",difficulty:"intermediate",category:"Phase 2: Functions",concepts:["recursion"],initialCode:"",hints:["Base case: if n <= 1: return 1","Recursive: return n * factorial(n-1)"],optimalTime:90,xpBase:290,testCases:[{input:"",expectedOutput:"120",hidden:false}]},
  {id:30,title:"Recursion - Fibonacci",description:"Write a recursive function `fibonacci(n)` that returns the nth Fibonacci number. Print `fibonacci(5)` (should be 5).",difficulty:"intermediate",category:"Phase 2: Functions",concepts:["recursion","fibonacci"],initialCode:"",hints:["Base: fib(0)=0, fib(1)=1","Recursive: return fib(n-1) + fib(n-2)"],optimalTime:90,xpBase:300,testCases:[{input:"",expectedOutput:"5",hidden:false}]},

  // Phase 3: Strings and Lists (31-40)
  {id:31,title:"String Slicing",description:'Given `s = "Hello, World!"`, use string slicing to extract and print just the word "World".',difficulty:"beginner",category:"Phase 3: Strings & Lists",concepts:["slicing"],initialCode:"",hints:["Use s[7:12]"],optimalTime:45,xpBase:310,testCases:[{input:"",expectedOutput:"World",hidden:false}]},
  {id:32,title:"String Methods",description:'Given `sentence = "the quick brown fox"`, print it in lowercase, then uppercase, then title case, each on a separate line.',difficulty:"beginner",category:"Phase 3: Strings & Lists",concepts:["lower","upper","title"],initialCode:"",hints:["Use .lower(), .upper(), .title()"],optimalTime:60,xpBase:320,testCases:[{input:"",expectedOutput:"the quick brown fox\nTHE QUICK BROWN FOX\nThe Quick Brown Fox",hidden:false}]},
  {id:33,title:"Split and Join",description:'Split the sentence "The quick brown fox" into words, then join them back with hyphens. Print the result.',difficulty:"beginner",category:"Phase 3: Strings & Lists",concepts:["split","join"],initialCode:"",hints:["Use .split() and '-'.join()"],optimalTime:60,xpBase:330,testCases:[{input:"",expectedOutput:"The-quick-brown-fox",hidden:false}]},
  {id:34,title:"Character Count",description:'Write a function `count_char(text, char)` that returns how many times `char` appears in `text`. Test with count_char("hello world", "l") and print the result.',difficulty:"intermediate",category:"Phase 3: Strings & Lists",concepts:["counting","loops"],initialCode:"",hints:["Loop through each character and count matches"],optimalTime:60,xpBase:340,testCases:[{input:"",expectedOutput:"3",hidden:false}]},
  {id:35,title:"Palindrome Checker",description:'Write a function `is_palindrome(s)` that returns True if s reads the same forwards and backwards (case insensitive). Test with "racecar".',difficulty:"intermediate",category:"Phase 3: Strings & Lists",concepts:["palindrome","string manipulation"],initialCode:"",hints:["Clean the string: s = s.lower()","Compare s == s[::-1]"],optimalTime:90,xpBase:350,testCases:[{input:"",expectedOutput:"True",hidden:false}]},
  {id:36,title:"List Comprehension - Squares",description:"Use a list comprehension to create a list of squares of numbers from 1 to 10. Print the list.",difficulty:"intermediate",category:"Phase 3: Strings & Lists",concepts:["list comprehension"],initialCode:"",hints:["[x**2 for x in range(1, 11)]"],optimalTime:45,xpBase:360,testCases:[{input:"",expectedOutput:"[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]",hidden:false}]},
  {id:37,title:"List Comprehension - Even Numbers",description:"From numbers 1 to 10, use a list comprehension with a condition to create a list of even numbers only. Print it.",difficulty:"intermediate",category:"Phase 3: Strings & Lists",concepts:["list comprehension","filter"],initialCode:"",hints:["Add an if condition: [x for x in range(1,11) if x % 2 == 0]"],optimalTime:45,xpBase:370,testCases:[{input:"",expectedOutput:"[2, 4, 6, 8, 10]",hidden:false}]},
  {id:38,title:"Enumerate",description:'Given `fruits = ["apple", "banana", "cherry"]`, use `enumerate` to print each fruit with its index in format "0: apple".',difficulty:"beginner",category:"Phase 3: Strings & Lists",concepts:["enumerate"],initialCode:"",hints:["for i, fruit in enumerate(fruits): print(f'{i}: {fruit}')"],optimalTime:45,xpBase:380,testCases:[{input:"",expectedOutput:"0: apple\n1: banana\n2: cherry",hidden:false}]},
  {id:39,title:"Zip",description:'Use `zip` to pair `names = ["Alice", "Bob", "Charlie"]` and `scores = [85, 92, 78]`, printing "Alice scored 85" etc.',difficulty:"intermediate",category:"Phase 3: Strings & Lists",concepts:["zip"],initialCode:"",hints:["for name, score in zip(names, scores):"],optimalTime:60,xpBase:390,testCases:[{input:"",expectedOutput:"Alice scored 85\nBob scored 92\nCharlie scored 78",hidden:false}]},
  {id:40,title:"List of Tuples Sorting",description:'Given `pairs = [("Alice", 85), ("Bob", 92), ("Charlie", 78)]`, sort by score in descending order using `sorted()` with a `key`. Print the sorted list.',difficulty:"intermediate",category:"Phase 3: Strings & Lists",concepts:["sorted","lambda","tuples"],initialCode:"",hints:["sorted(pairs, key=lambda x: x[1], reverse=True)"],optimalTime:90,xpBase:400,testCases:[{input:"",expectedOutput:"[('Bob', 92), ('Alice', 85), ('Charlie', 78)]",hidden:false}]},

  // Phase 4: Dictionaries and File I/O (41-50)
  {id:41,title:"Creating a Dictionary",description:'Create a dictionary `student = {"name": "Alice", "age": 20, "grade": "A"}`. Print it.',difficulty:"beginner",category:"Phase 4: Dicts & File I/O",concepts:["dictionaries"],initialCode:"",hints:["Use curly braces {} with key: value pairs"],optimalTime:45,xpBase:410,testCases:[{input:"",expectedOutput:"{'name': 'Alice', 'age': 20, 'grade': 'A'}",hidden:false}]},
  {id:42,title:"Accessing Dictionary Values",description:'Given `student = {"name": "Alice", "age": 20, "grade": "A"}`, print the name and age on separate lines.',difficulty:"beginner",category:"Phase 4: Dicts & File I/O",concepts:["dict access"],initialCode:"",hints:["Use student['name'] and student['age']"],optimalTime:45,xpBase:420,testCases:[{input:"",expectedOutput:"Alice\n20",hidden:false}]},
  {id:43,title:"Adding and Updating",description:'Given `student = {"name": "Alice", "age": 20, "grade": "A"}`, add "major": "Computer Science" and update grade to "A+". Print the final dictionary.',difficulty:"beginner",category:"Phase 4: Dicts & File I/O",concepts:["dict update"],initialCode:"",hints:["student['major'] = 'Computer Science' and student['grade'] = 'A+'"],optimalTime:60,xpBase:430,testCases:[{input:"",expectedOutput:"{'name': 'Alice', 'age': 20, 'grade': 'A+', 'major': 'Computer Science'}",hidden:false}]},
  {id:44,title:"Looping through a Dictionary",description:'Given `student = {"name": "Alice", "age": 20, "grade": "A"}`, loop through and print each "key: value" on separate lines.',difficulty:"beginner",category:"Phase 4: Dicts & File I/O",concepts:["dict iteration"],initialCode:"",hints:["for key, value in student.items(): print(f'{key}: {value}')"],optimalTime:60,xpBase:440,testCases:[{input:"",expectedOutput:"name: Alice\nage: 20\ngrade: A",hidden:false}]},
  {id:45,title:"Word Frequency Counter",description:'Write a function `word_count(sentence)` that returns a dict of word frequencies. Test with "the cat and the dog".',difficulty:"intermediate",category:"Phase 4: Dicts & File I/O",concepts:["dict","counting"],initialCode:"",hints:["Split sentence into words, loop and count using a dict"],optimalTime:90,xpBase:450,testCases:[{input:"",expectedOutput:"{'the': 2, 'cat': 1, 'and': 1, 'dog': 1}",hidden:false}]},
  {id:46,title:"Simulated File Reading",description:'Given a multi-line string `text = """Hello World\\nPython is great\\nI love coding"""`, loop through the lines and print each one.',difficulty:"intermediate",category:"Phase 4: Dicts & File I/O",concepts:["file reading","string splitting"],initialCode:"",hints:["Use text.strip().split('\\n') to get lines"],optimalTime:60,xpBase:460,testCases:[{input:"",expectedOutput:"Hello World\nPython is great\nI love coding",hidden:false}]},
  {id:47,title:"Simulated File Writing",description:'Simulate file operations: create a list called `content`, append "Hello World" and "New line added", then print each line.',difficulty:"intermediate",category:"Phase 4: Dicts & File I/O",concepts:["file writing"],initialCode:"",hints:["Use a list as a buffer, append lines, then print"],optimalTime:60,xpBase:470,testCases:[{input:"",expectedOutput:"Hello World\nNew line added",hidden:false}]},
  {id:48,title:"Counting Lines",description:'Given a multi-line string with 5 lines, count and print the number of lines.',difficulty:"intermediate",category:"Phase 4: Dicts & File I/O",concepts:["file operations","len"],initialCode:"",hints:["Split by newline and use len()"],optimalTime:45,xpBase:480,testCases:[{input:"",expectedOutput:"5",hidden:false}]},
  {id:49,title:"Word Frequency from Text",description:'Given `text = "the cat and the dog and the fish"`, count word frequencies and print the dictionary.',difficulty:"intermediate",category:"Phase 4: Dicts & File I/O",concepts:["word frequency"],initialCode:"",hints:["Split text into words, use a dict to count"],optimalTime:90,xpBase:490,testCases:[{input:"",expectedOutput:"{'the': 3, 'cat': 1, 'and': 2, 'dog': 1, 'fish': 1}",hidden:false}]},
  {id:50,title:"Most Common Word",description:'Given `freq = {"the": 3, "cat": 1, "and": 2, "dog": 1}`, find and print the word with the highest count.',difficulty:"intermediate",category:"Phase 4: Dicts & File I/O",concepts:["dict","max finding"],initialCode:"",hints:["Loop through items, track the one with highest value"],optimalTime:60,xpBase:500,testCases:[{input:"",expectedOutput:"the",hidden:false}]}
];

// Phase 5-9: Generate remaining 50 questions
const advancedQuestions = [
  {id:51,title:"Clean Text Function",desc:"Write `clean_text(text)` that converts to lowercase and removes punctuation. Test with a sample sentence.",diff:"intermediate",cat:"Phase 5: Bigram Model",con:["string cleaning"]},
  {id:52,title:"Tokenize Function",desc:"Write `tokenize(text)` that cleans text and splits into words. Return the list of tokens.",diff:"intermediate",cat:"Phase 5: Bigram Model",con:["tokenization"]},
  {id:53,title:"Build Vocabulary",desc:"Write `build_vocab(tokens)` returning `word_to_id` and `id_to_word` dictionaries.",diff:"intermediate",cat:"Phase 5: Bigram Model",con:["vocabulary","dictionaries"]},
  {id:54,title:"Convert Tokens to IDs",desc:"Write `tokens_to_ids(tokens, word_to_id)` converting a list of word tokens to integer IDs.",diff:"intermediate",cat:"Phase 5: Bigram Model",con:["mapping","encoding"]},
  {id:55,title:"Load Corpus",desc:"Write `load_corpus(text)` that cleans, tokenizes, and builds vocab from raw text. Return tokens, vocab.",diff:"intermediate",cat:"Phase 5: Bigram Model",con:["pipeline","corpus"]},
  {id:56,title:"Unigram Counts",desc:"Write `count_unigrams(ids, vocab_size)` that returns a list of counts for each word ID.",diff:"intermediate",cat:"Phase 5: Bigram Model",con:["counting","unigrams"]},
  {id:57,title:"Print Top Words",desc:"Given unigram counts and `id_to_word`, print the top 5 most frequent words.",diff:"intermediate",cat:"Phase 5: Bigram Model",con:["sorting","frequency"]},
  {id:58,title:"Bigram Counts",desc:"Write `count_bigrams(ids, vocab_size)` returning a 2D list (matrix) of bigram counts.",diff:"advanced",cat:"Phase 5: Bigram Model",con:["bigrams","matrix"]},
  {id:59,title:"Bigram Probabilities",desc:"Convert bigram count matrix to probability matrix by normalizing each row.",diff:"advanced",cat:"Phase 5: Bigram Model",con:["probability","normalization"]},
  {id:60,title:"Sentence Probability",desc:"Write `sentence_probability(ids, probs)` that computes the log probability of a sequence.",diff:"advanced",cat:"Phase 5: Bigram Model",con:["log probability","evaluation"]},
  {id:61,title:"Simple Text Generator",desc:"Write `generate(start_id, probs, id_to_word, max_length)` using random sampling from probabilities.",diff:"advanced",cat:"Phase 6: Text Generation",con:["generation","random"]},
  {id:62,title:"IDs to Sentence",desc:"Write `ids_to_sentence(ids, id_to_word)` that joins word strings with spaces.",diff:"intermediate",cat:"Phase 6: Text Generation",con:["decoding"]},
  {id:63,title:"Interactive Generator",desc:"Ask user for a starting word, look up its ID, generate a sentence, and print it.",diff:"advanced",cat:"Phase 6: Text Generation",con:["interactive","input"]},
  {id:64,title:"Add-K Smoothing",desc:"Implement add-k smoothing for bigram probabilities to handle unseen bigrams.",diff:"advanced",cat:"Phase 6: Text Generation",con:["smoothing","probability"]},
  {id:65,title:"Compare Smoothed vs Raw",desc:"Generate with both raw and smoothed probabilities. Print both outputs for comparison.",diff:"advanced",cat:"Phase 6: Text Generation",con:["comparison","smoothing"]},
  {id:66,title:"Perplexity",desc:"Implement `perplexity(ids, probs)` as 2^(avg negative log probability).",diff:"advanced",cat:"Phase 6: Text Generation",con:["perplexity","evaluation"]},
  {id:67,title:"Train/Test Split",desc:"Write `split_data(ids, ratio=0.8)` returning train and test ID lists.",diff:"intermediate",cat:"Phase 6: Text Generation",con:["data splitting"]},
  {id:68,title:"Evaluate Model",desc:"Build bigram model on train set, compute perplexity on test set. Print results.",diff:"advanced",cat:"Phase 6: Text Generation",con:["evaluation","pipeline"]},
  {id:69,title:"Temperature Sampling",desc:"Modify generate() with a temperature parameter. Implement softmax with temperature manually.",diff:"advanced",cat:"Phase 6: Text Generation",con:["temperature","softmax"]},
  {id:70,title:"Temperature Experiments",desc:"Generate sentences at temperatures 0.5, 1.0, 1.5. Print all three and observe differences.",diff:"advanced",cat:"Phase 6: Text Generation",con:["experimentation"]},
  {id:71,title:"N-gram Model Class",desc:"Write an NGramModel class that generalizes to any n value. Include count and probability methods.",diff:"advanced",cat:"Phase 7: N-gram & Neural",con:["classes","n-grams"]},
  {id:72,title:"Bigram vs Trigram",desc:"Create NGramModel with n=2 and n=3, generate text from both, and print for comparison.",diff:"advanced",cat:"Phase 7: N-gram & Neural",con:["trigram","comparison"]},
  {id:73,title:"Random Embeddings",desc:"Write `random_embeddings(vocab_size, embed_dim)` returning a 2D list of random floats between -1 and 1.",diff:"intermediate",cat:"Phase 7: N-gram & Neural",con:["embeddings","random"]},
  {id:74,title:"Cosine Similarity",desc:"Implement `cosine_similarity(vec1, vec2)` computing dot product over product of magnitudes.",diff:"intermediate",cat:"Phase 7: N-gram & Neural",con:["cosine similarity","vectors"]},
  {id:75,title:"Most Similar Words",desc:"Write `most_similar(word_id, embeddings, id_to_word, top_k=5)` returning most similar words by cosine.",diff:"advanced",cat:"Phase 7: N-gram & Neural",con:["similarity search"]},
  {id:76,title:"Co-occurrence Matrix",desc:"Build a co-occurrence matrix from token IDs using a sliding window of configurable size.",diff:"advanced",cat:"Phase 7: N-gram & Neural",con:["co-occurrence","matrix"]},
  {id:77,title:"PPMI",desc:"Convert co-occurrence matrix to Positive Pointwise Mutual Information values.",diff:"advanced",cat:"Phase 7: N-gram & Neural",con:["PPMI","statistics"]},
  {id:78,title:"Compare Word Similarities",desc:"Compare similarities using random embeddings vs co-occurrence vs PPMI vectors.",diff:"advanced",cat:"Phase 7: N-gram & Neural",con:["comparison","evaluation"]},
  {id:79,title:"Simple Neural Layer",desc:"Write a Linear class with __init__(in_dim, out_dim) and forward(x) using manual matrix multiply.",diff:"advanced",cat:"Phase 7: N-gram & Neural",con:["neural network","linear layer"]},
  {id:80,title:"Activation Functions",desc:"Implement ReLU (max(0,x)) and Softmax (exp normalization) classes with forward methods.",diff:"advanced",cat:"Phase 7: N-gram & Neural",con:["ReLU","softmax"]},
  {id:81,title:"One-Hot Encoding",desc:"Write `one_hot(word_id, vocab_size)` that returns a list of 0s with a 1 at the word_id position.",diff:"intermediate",cat:"Phase 8: Neural Network",con:["one-hot","encoding"]},
  {id:82,title:"Two-Layer Network",desc:"Create BigramNN with hidden layer, ReLU activation, output layer, and softmax. Implement forward().",diff:"advanced",cat:"Phase 8: Neural Network",con:["neural network","forward pass"]},
  {id:83,title:"Cross-Entropy Loss",desc:"Implement `cross_entropy_loss(predictions, target_id)` as -log(predictions[target_id]).",diff:"advanced",cat:"Phase 8: Neural Network",con:["cross-entropy","loss"]},
  {id:84,title:"Manual Gradient",desc:"Compute the gradient of cross-entropy loss w.r.t. softmax output. Print gradient vector.",diff:"advanced",cat:"Phase 8: Neural Network",con:["gradients","backprop"]},
  {id:85,title:"Backward Pass",desc:"Add backward() methods to Linear and ReLU classes for gradient computation.",diff:"advanced",cat:"Phase 8: Neural Network",con:["backpropagation"]},
  {id:86,title:"Training Step",desc:"Write `train_step(model, input_id, target_id, lr)` performing forward, loss, backward, update.",diff:"advanced",cat:"Phase 8: Neural Network",con:["training","gradient descent"]},
  {id:87,title:"Train on Corpus",desc:"Loop through training IDs calling train_step. Print loss every 100 steps.",diff:"advanced",cat:"Phase 8: Neural Network",con:["training loop"]},
  {id:88,title:"Mini-Batches",desc:"Implement `get_batches(ids, batch_size)` and modify training to use batches.",diff:"advanced",cat:"Phase 8: Neural Network",con:["batching","training"]},
  {id:89,title:"Validation",desc:"Split data into train/val, compute perplexity on validation set. Implement early stopping.",diff:"advanced",cat:"Phase 8: Neural Network",con:["validation","early stopping"]},
  {id:90,title:"Generate with Neural Model",desc:"Write `generate_neural(model, start_id, length)` sampling from neural network output.",diff:"advanced",cat:"Phase 8: Neural Network",con:["generation","neural"]},
  {id:91,title:"Scaled Dot-Product Attention",desc:"Implement attention(Q, K, V) with scaled dot product: softmax(QK^T/sqrt(d))V.",diff:"advanced",cat:"Phase 9: Mini Transformer",con:["attention","dot product"]},
  {id:92,title:"Multi-Head Attention",desc:"Implement single attention head with learnable W_q, W_k, W_v projection matrices.",diff:"advanced",cat:"Phase 9: Mini Transformer",con:["attention heads"]},
  {id:93,title:"Layer Normalization",desc:"Implement LayerNorm class that normalizes across the last dimension with learnable gamma/beta.",diff:"advanced",cat:"Phase 9: Mini Transformer",con:["layer norm"]},
  {id:94,title:"Feed-Forward Network",desc:"Create FeedForward class with two Linear layers and ReLU activation in between.",diff:"advanced",cat:"Phase 9: Mini Transformer",con:["feed-forward"]},
  {id:95,title:"Transformer Block",desc:"Assemble TransformerBlock with attention, residual connection, layernorm, and feedforward.",diff:"advanced",cat:"Phase 9: Mini Transformer",con:["transformer","residual"]},
  {id:96,title:"Positional Encoding",desc:"Write `positional_encoding(seq_len, d_model)` using sine/cosine functions.",diff:"advanced",cat:"Phase 9: Mini Transformer",con:["positional encoding"]},
  {id:97,title:"Mini Transformer Model",desc:"Create MiniTransformer combining embedding, positional encoding, and stacked transformer blocks.",diff:"advanced",cat:"Phase 9: Mini Transformer",con:["transformer model"]},
  {id:98,title:"Train Mini Transformer",desc:"Train the transformer on sequences with teacher forcing and causal masking.",diff:"advanced",cat:"Phase 9: Mini Transformer",con:["training","causal masking"]},
  {id:99,title:"Beam Search",desc:"Implement beam search decoding maintaining top-k hypotheses at each step.",diff:"advanced",cat:"Phase 9: Mini Transformer",con:["beam search","decoding"]},
  {id:100,title:"Final Integration",desc:"Build the complete pipeline: load data, train model, accept input, generate with beam search.",diff:"advanced",cat:"Phase 9: Mini Transformer",con:["integration","pipeline"]}
];

// Expand advanced questions
advancedQuestions.forEach(q => {
  questions.push({
    id: q.id,
    title: q.title,
    description: q.desc,
    difficulty: q.diff,
    category: q.cat,
    concepts: q.con,
    initialCode: "",
    hints: [`Think about how ${q.con[0]} works`, "Break the problem into smaller steps"],
    optimalTime: q.diff === 'advanced' ? 300 : 120,
    xpBase: q.id * 10,
    subjective: true,
    testCases: [{type:"compile_only",description:"Code must compile successfully"}]
  });
});

// Write to file
const dataDir = path.join(__dirname, '..', 'data');
if (!fs.existsSync(dataDir)) fs.mkdirSync(dataDir, { recursive: true });
fs.writeFileSync(path.join(dataDir, 'questions.json'), JSON.stringify(questions, null, 2));
console.log(`Generated ${questions.length} questions to data/questions.json`);
console.log('All initialCode fields are EMPTY — no pre-filled answers!');
